server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  redis:
    host: ${REDIS_HOST:redis_1}
    port: ${REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    com.back: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    io.lettuce.core: WARN
    org.springframework.data.redis: WARN
custom:
  site:
    cookie:
      secure: true
      sameSite: None
    cookieDomain: ${COOKIE_DOMAIN}
    frontUrl: ${FRONT_URL}"
    backUrl: ${BACK_URL}
  genFile:
    dirPath: /gen
